Feature pagepost
felipejuzo02/quasar-blog pull request #1
Opened 2021-03-26 14:50 UTC by felipejuzo02

Your monicas <3

2021-03-26 17:39 UTC, eliasassuncao requested changes

2021-03-26 17:55 UTC, eliasassuncao requested changes

2021-03-26 17:55 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +  // .teste{
estilo comentado

2021-03-26 17:55 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +    position: relative;
existe classe pra isso ja

2021-03-26 17:55 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      <div class="col-sm-3 col-12 page-list__card">
classe `page-list__card`  não existe

2021-03-26 17:55 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="vAuthor" :options='opauthor' label="Autor" />
v-model poderia ter um nome mais semantico, acho que só `author` ja ficaria melhor. O mesmo pra os options, poderia ser `authorOptions`

2021-03-26 17:55 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="vCategory" :options='opcategory' label="Categoria" />
v-model poderia ter um nome mais semantico, acho que só `category` ja ficaria melhor. O mesmo pra os options, poderia ser `categoryOptions`

2021-03-26 17:55 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="vData" :options='opdata' label="Data" />
isso não seria melhor ser um campo type data?

2021-03-26 17:55 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +    <div class="q-pa-lg flex flex-center page-list__pagination">
classe `page-list__pagination` não existe

2021-03-26 18:16 UTC, cassioalmeida2 requested changes

2021-03-30 12:13 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    background-color: white;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:13 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    border-radius: 30px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    position: relative;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      position: absolute;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      background-color: $primary;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    &__category{
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      color: white;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      padding: 3px 10px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      border-radius: 10px 0 0 10px
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      border-top-left-radius: 30px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:14 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      border-top-right-radius: 30px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      width: 100%;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +        font-size: 28px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +        margin: 0 10px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      margin: 0 10px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      font-size: 12px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      display: flex;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      align-items: center;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      margin: 20px 10px 10px 10px;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:15 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +        border-radius: 50%;
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:16 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      & p{
O card será realizado apenas com SCSS, evitando o uso do quasar nessa situação

2021-03-30 12:17 UTC, felipejuzo02 commented on src/components/EssentialLink.vue
> +    color: white;
O estilo foi retirado devido essa definição de cor ser desnecessária

2021-03-30 12:29 UTC, felipejuzo02 commented on src/pages/authors/AuthorsCreate.vue
> +      <div class="page-authors-create__top flex justify-between">
Classes removidas

2021-03-30 12:30 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +      <div class="page-authors__information">
Classes removidas

2021-03-30 12:30 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      <div class="page-create__information">
Classes removidas

2021-03-30 12:30 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +  // .teste{
Estilo removido

2021-03-30 12:30 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      <div class="col-sm-3 col-12 page-list__card">
Classes removida

2021-03-30 12:32 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="vData" :options='opdata' label="Data" />
Alterado

2021-03-30 12:45 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +    <div class="q-pa-lg flex flex-center page-list__pagination">
Removida

2021-03-30 14:38 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +        line-height: 36px;
Utilizada para definir o tamanho da linha do titulo do post, podendo ser substituído por padding/margin para dar espaçamento no eixo Y. O uso foi mais por questão de escolha opcional.

2021-03-30 14:46 UTC, eliasassuncao requested changes

2021-03-30 14:46 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +    <q-drawer show-if-above v-model="left" side="left" bordered content-class="bg-white " class="main-layout__drawer fixed-left">
`main-layout__drawer`classe não existente

2021-03-30 14:46 UTC, eliasassuncao commented on src/layouts/MainLayout.vue
> +      group: null
vc utiliza esse group pra algo? caso não use, pode remover.

2021-03-30 14:46 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      <div class="page-list__top flex justify-between">
remover classes não existentes nesse arquivo:

`page-list__information`, `page-list__top`, `page-list__path`, `page-list__filter`, `page-list__pagination`

2021-03-30 14:46 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +  <q-page class="bg-grey-2 q-pa-lg page-list">
o padrão pra o nome de classe que utilizamos é:

se for uma `page`, é sempre `page-${pageName}`, então no caso seria `page-posts-list`. Caso o `PostsList.vue` fosse um componente, seria somente `posts-list`

2021-03-30 14:46 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +  },
adicionar quebra de linha

2021-03-30 14:46 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +import CardPost from 'src/components/CardPost.vue'
adicionar quebra de linha

2021-03-30 14:46 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      width: 90%;
width muito especifico, não teria uma forma melhor?

2021-03-30 14:49 UTC, cassioalmeida2 commented on src/components/CardPost.vue
> +        line-height: 36px;
Show, ok, em alguns cenários vamos poder definir isso já no quasar, e dependendo o projeto já estará configurado esse line-height para você usar.

2021-03-30 14:50 UTC, cassioalmeida2 approved these changes

2021-03-30 14:54 UTC, felipejuzo02 commented on src/layouts/MainLayout.vue
> +    <q-drawer show-if-above v-model="left" side="left" bordered content-class="bg-white " class="main-layout__drawer fixed-left">
Removido

2021-03-30 14:54 UTC, felipejuzo02 commented on src/layouts/MainLayout.vue
> +      group: null
Removido

2021-03-30 14:55 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      <div class="page-list__top flex justify-between">
Removido

2021-03-30 14:57 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +  <q-page class="bg-grey-2 q-pa-lg page-list">
alterado

2021-03-30 14:57 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +  },
Adicionado

2021-03-30 14:58 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +import CardPost from 'src/components/CardPost.vue'
Adicionado

2021-03-30 15:04 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      width: 90%;
Alterado para col

2021-03-30 15:28 UTC, eliasassuncao requested changes

2021-03-30 15:28 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +      <div>
precisa dessa div?

2021-03-30 15:29 UTC, felipejuzo02 commented on src/layouts/MainLayout.vue
> +          <q-item-section >Home</q-item-section>
Removido

2021-03-30 15:31 UTC, merged