Feature authors
felipejuzo02/quasar-blog pull request #2
Opened 2021-04-06 11:42 UTC by felipejuzo02

2021-04-06 14:25 UTC, eliasassuncao requested changes

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +          <q-btn color="primary" label="Criar" @click='addAuthorToList' />
utilizar aspas duplas para propriedades, `@click="addAuthorToList"`

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +          <q-btn color="primary" flat label="Cancelar" @click='confirmCancel' />
utilizar aspas duplas para propriedades, `@click="confirmCancel"`

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +                <q-btn  label="Confirmar" color="primary" v-close-popup :to="{name: 'AuthorsList' }" />
remover espaçamento a mais antes do label, e adicionar espaço antes do `name`

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +      if (this.name.length < 3 || this.name.length < 3) {
if não utilizado, e pra validação de campo vc pode utilizar um `rules`

https://quasar.dev/vue-components/input#validation

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +          <q-btn color="primary" label="Editar" @click='editListAuthor' />
utilizar aspas duplas para propriedades, @click="editListAuthor"

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +          <q-btn color="primary" flat label="Cancelar" @click="confirmCancel" />
utilizar aspas duplas para propriedades, @click="confirmCancel"

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +                <q-btn  label="Confirmar" color="primary" v-close-popup :to="{name: 'AuthorsList' }" />
remover espaçamento a mais antes do label, e adicionar espaço antes do name

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +      if (this.name.length < 3 || this.name.length < 3) {
if não utilizado, e pra validação de campo vc pode utilizar um rules

https://quasar.dev/vue-components/input#validation

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +    this.name = this.authors[this.$route.params.id].name
this.$route.params.id sendo utilizado em varios lugares, poderia ser uma computada

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +    this.email = this.authors[this.$route.params.id].email
seria melhor isolar essas atribuições de valores em uma função

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +                        <q-btn flat :to="{ name: 'AuthorsEdit', params: { id: index }}">Editar</q-btn>
espaçamento dps do `{ id: index }`

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
>          <q-btn icon="add" unelevated rounded color="primary" label="Adicionar autor" :to="{ name: 'AuthorsCreate'}" />
espaçamento dps do 'AuthorsCreate'

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +                    <q-item clickable >
remover espaçamento dps do clickable

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +                        <q-btn flat class="text-red" @click="confirmDelete = true">Excluir</q-btn>
remover lógica na view `@click="confirmDelete = true"`, deverá ser um method

2021-04-06 14:25 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +                      </q-dialog>
identação está certa ? me parece errada

2021-04-06 14:25 UTC, eliasassuncao commented on src/store/index.js
> +import authors from './module-example/authors'
criar uma pasta chamada `modules` e colocar seu modulo. Remover a pasta de exemplo.

2021-04-06 14:25 UTC, eliasassuncao commented on src/store/module-example/authors.js
> +  authorsList: state => {
não precisa das chaves, a função não tem lógica, só retorna o `state.authors`, somente `authorsList: state => state.authors`  já funciona

2021-04-06 15:13 UTC, felipejuzo02 commented on src/pages/authors/AuthorsCreate.vue
> +          <q-btn color="primary" label="Criar" @click='addAuthorToList' />
Resolvido

2021-04-06 15:13 UTC, felipejuzo02 commented on src/pages/authors/AuthorsCreate.vue
> +          <q-btn color="primary" flat label="Cancelar" @click='confirmCancel' />
Resolvido

2021-04-06 15:13 UTC, felipejuzo02 commented on src/pages/authors/AuthorsCreate.vue
> +                <q-btn  label="Confirmar" color="primary" v-close-popup :to="{name: 'AuthorsList' }" />
Resolvido

2021-04-06 15:15 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +          <q-btn color="primary" label="Editar" @click='editListAuthor' />
Resolvido

2021-04-06 15:16 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +          <q-btn color="primary" flat label="Cancelar" @click="confirmCancel" />
Resolvido

2021-04-06 15:17 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +                <q-btn  label="Confirmar" color="primary" v-close-popup :to="{name: 'AuthorsList' }" />
Resolvido

2021-04-06 15:24 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +                        <q-btn flat :to="{ name: 'AuthorsEdit', params: { id: index }}">Editar</q-btn>
Resolvido

2021-04-06 15:24 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
>          <q-btn icon="add" unelevated rounded color="primary" label="Adicionar autor" :to="{ name: 'AuthorsCreate'}" />
Resolvido

2021-04-06 15:24 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +                    <q-item clickable >
Resolvido

2021-04-06 15:26 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +                        <q-btn flat class="text-red" @click="confirmDelete = true">Excluir</q-btn>
Resolvido

2021-04-06 16:30 UTC, felipejuzo02 commented on src/store/index.js
> +import authors from './module-example/authors'
Resolvido

2021-04-06 16:31 UTC, felipejuzo02 commented on src/store/module-example/authors.js
> +  authorsList: state => {
Resolvido

2021-04-06 16:37 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +                      </q-dialog>
identação ajustada

2021-04-06 18:50 UTC, felipejuzo02 commented on src/pages/authors/AuthorsCreate.vue
> +      if (this.name.length < 3 || this.name.length < 3) {
Utilizei rules para fazer a verificação, mas também dentro do if, coloquei um data que servirá para mudar o valor do v-show para exibir uma mensagem caso o campo não tenha sido preenchido conforme regras
![image](https://user-images.githubusercontent.com/79236683/113763248-db911280-96ef-11eb-9fce-c580acc5a609.png)

2021-04-06 18:52 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +      if (this.name.length < 3 || this.name.length < 3) {
Utilizei rules para fazer a verificação, mas também dentro do if, coloquei um data que servirá para mudar o valor do v-show para exibir uma mensagem caso o campo não tenha sido preenchido conforme regras

![image](https://user-images.githubusercontent.com/79236683/113763407-0b401a80-96f0-11eb-84df-a39e2225d484.png)

2021-04-06 18:53 UTC, felipejuzo02 commented on src/pages/authors/AuthorsCreate.vue
> +      if (this.name.length < 3 || this.name.length < 3) {
![image](https://user-images.githubusercontent.com/79236683/113763573-3296e780-96f0-11eb-9335-dc2ba01c685e.png)

2021-04-06 18:56 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +    this.email = this.authors[this.$route.params.id].email
Resolvido

2021-04-06 21:16 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +    this.name = this.authors[this.$route.params.id].name
Resolvido

2021-04-06 21:29 UTC, cassioalmeida2 approved these changes

2021-04-06 21:29 UTC, cassioalmeida2 commented on src/pages/authors/AuthorsList.vue
> +                  <q-item clickable>
Para que está utilizando o clickable nesse momento?

2021-04-06 21:29 UTC, cassioalmeida2 commented on src/pages/authors/AuthorsList.vue
> +      this.$q.notify({
o que o $q faz?

2021-04-06 21:29 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
>          <q-input v-model="text" label="Procurar" class="page-posts-list__search col" />
para que a classe col está sendo utilizada neste caso?

2021-04-06 21:33 UTC, eliasassuncao requested changes

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        <q-input outlined v-model="name" label="Nome do autor" class="q-my-md" :rules="[ val => val.length >= 3 || 'É necessário no mínimo 3 caracteres']" />
validação nunca na view, criar um método pra isso, ou melhor, um helper, já q vc reutiliza essa validação.

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        <q-input outlined v-model="email" label="E-mail" suffix="@gmail.com" :rules="[ val => val.length >= 3 || 'E-mail digitado não é válido']" />
o mesmo pra esse rules

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        <q-input outlined v-model="email" label="E-mail" suffix="@gmail.com" :rules="[ val => val.length >= 3 || 'E-mail digitado não é válido']" />
e seu quiser enviar um e-mail sem ser gmail?

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        this.addAuthors({ name: this.name, email: this.email + '@gmail.com' })
não seria melhor sem `suffix` ?

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +            </q-card-actions>
identação não parece estar certa

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        this.checkFilledFields = true
vc poderia utilizar

```
this.checkFilledFields = true
return
```

pra remover o else

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +        <q-input outlined v-model="email" label="E-mail" :rules="[ val => val.length >= 13 || 'E-mail digitado não é válido']" />
lógica na view

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +        <q-input outlined v-model="name" label="Nome do autor" class="q-my-md" :rules="[ val => val.length >= 3 || 'É necessário no mínimo 3 caracteres']" />
lógica na view

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +        <small class="text-negative" v-show="checkFilledFields" >Todos os campos devem ser preenchidos</small>
espaço desnecessário dps do `checkFilledFields`

2021-04-06 21:33 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        this.checkFilledFields = true
não seria melhor vc desabilitar o botão caso os campos não forem preenchidos? pra prevenir o erro o usuário.

2021-04-07 13:01 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +        <q-input outlined v-model="name" label="Nome do autor" class="q-my-md" :rules="[ val => val.length >= 3 || 'É necessário no mínimo 3 caracteres']" />
Resolvido

2021-04-07 13:01 UTC, felipejuzo02 commented on src/pages/authors/AuthorsEdit.vue
> +        <q-input outlined v-model="email" label="E-mail" :rules="[ val => val.length >= 13 || 'E-mail digitado não é válido']" />
Resolvido

2021-04-07 13:03 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +                  <q-item clickable>
Todo o campo estava com o estilo de clicável, mas alterei para apenas o botão ter esse estilo removendo o clickable

2021-04-08 13:59 UTC, eliasassuncao requested changes

2021-04-08 13:59 UTC, eliasassuncao commented on src/helpers/methods/validateFields.js
> +function validateRequiredFields (name) {
o nome do parâmetro poderia ser `field`, já q eu posso utilizar esse helper de validação pra outros campos q não sejam `name`

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        <q-input outlined v-model="name" label="Nome do autor" class="q-my-md" :rules="[ val => validateRequiredFields(this.name) ]" />
vc passando o rules dessa forma não funciona? `:rules="[validateRequiredFields(this.name)]"`

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +        <q-input outlined v-model="email" label="E-mail" :rules="[ val => validateEmailFields(this.email) ]" />
vc passando o rules dessa forma não funciona? `:rules="[validateEmailFields(this.name)]"`

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +    validateRequiredFields,
faltou quebrar linha

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +      this.checkFilledFields = false
essa chave `checkFilledFields` está sendo utilizda pra algo?

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsCreate.vue
> +      this.checkFilledFields = false
essa chave `checkFilledFields` está sendo utilizda pra algo?

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +        <q-input outlined v-model="name" label="Nome do autor" class="q-my-md" :rules="[ val => validateRequiredFields(this.name) ]" />
essa chave checkFilledFields está sendo utilizda pra algo?

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +        <q-input outlined v-model="email" label="E-mail" :rules="[ val => validateEmailFields(this.email) ]" />
essa chave checkFilledFields está sendo utilizda pra algo?

2021-04-08 13:59 UTC, eliasassuncao commented on src/pages/authors/AuthorsEdit.vue
> +    validateRequiredFields,
faltou quebrar linha

2021-04-08 18:05 UTC, eliasassuncao approved these changes

2021-04-08 18:31 UTC, merged