Feature page post
felipejuzo02/quasar-blog pull request #3
Opened 2021-04-14 18:33 UTC by felipejuzo02

2021-04-14 19:38 UTC, eliasassuncao requested changes

2021-04-14 19:38 UTC, eliasassuncao commented on src/components/CardPost.vue
> +    <div class="card-post__click" v-on="$listeners">
nome de classe sem sentido, deveria ser o que essa div é responsável.

2021-04-14 19:38 UTC, eliasassuncao commented on src/components/CardPost.vue
> +   &__click{
já existe a classe `cursor-pointer`

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +      titulo: 'teste',
propriedade deve ser em inglês, e essa propriedade não é utilizada em nenhum lugar.

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsCreate.vue
> +        <q-editor class="q-my-lg bg-grey-2" v-model="mainText" :definitions="{ bold: {label: 'Bold', icon: null} }"/>
precisa desse `icon: null` ?

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsCreate.vue
> +      this.addPost({ urlMainImage: this.urlMainImage, category: this.selectedCategory, title: this.title, shortDescription: this.shortDescription, authorName: this.selectedAuthor, postDate: this.post
não seria melhor vc ter um values no data, q engloba todos valores q vc precisa enviar?
ai vc só precisa passar a chave values pro `this.addPost(this.values)`

```
values: {
 urlMainImage: '',
 category: '',
 ....
}

```

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsCreate.vue
> +      return !!(this.validateRequiredFields(this.urlMainImage) || (this.validateRequiredFields(this.title)) ||
vc tendo o `values`, vc poderia fazer uma lógica loopando as chaves e ir validando

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsCreate.vue
> +          <q-dialog v-model="confirmCancelData" persistent>
percebi q tem esse modal em vários lugares, não seria melhor ser um componente?

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsEdit.vue
> +      this.urlMainImage = this.posts[this.idPost].urlMainImage
vc não poderia loopar? caso tivesse um `values` com essas propriedades

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsEdit.vue
> +      authorsList: 'authors/authorsList'
vc poderia utilizar essa chave no outro mapGetters

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsEdit.vue
> +      return !!(this.validateRequiredFields(this.urlMainImage) || (this.validateRequiredFields(this.title)) ||
com o `values`, poderia ter uma lógica loopando pra validação

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="selectedAuthor" :options='authorsOptions' label="Autor" />
os options estão com aspas simples, deveria ser aspas duplas

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="selectedCategory" :options='categoryOptions' label="Categoria" />
os options estão com aspas simples, deveria ser aspas duplas

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsEdit.vue
> +        values: {
se fosse um `values` com as propriedades era só usar `values: this.values`

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsEdit.vue
> +    idPost () {
não seria postId ?

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +    <div v-if="checkListSizeForPagination()" class="q-pa-lg flex flex-center">
não poderia ser uma computada?

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      this.$router.push({ name: 'PostsSingle', params: { id: index } })
vc poderia chamar o parametro de index, e utilizar somente `params: { id }` ao invés de `params: { id: index }`

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      this.selectedAuthor = ''
se tivesse um values vc looparia pra limpar

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +    &__edit{
por que dessa classe?

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +  .page-post-list{
espaçamento dps do `.page-post-list`

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +    loadValues () {
se tivesse um `values`, poderia loopar pra setar o valor

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +  <q-page class="bg-grey-2 q-pa-lg page-posts-preview">
nome da página não condiz com a classe, deveria ser `page-posts` somente

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +    &__category{
qual a necessidade desse height?

2021-04-14 19:38 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +  .page-posts-preview{
espaçamento depois do  `.page-posts-preview`

2021-04-14 19:42 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +    <div class="card-post__click" v-on="$listeners">
Nome da classe alterada para o cursor-pointer e remoçao do css atribuido a ela

2021-04-14 19:42 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +   &__click{
Alterado

2021-04-14 19:43 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +      titulo: 'teste',
propriedade removida

2021-04-14 19:44 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +        <q-editor class="q-my-lg bg-grey-2" v-model="mainText" :definitions="{ bold: {label: 'Bold', icon: null} }"/>
toda parte de definição foi removida para melhor layout

2021-04-14 19:46 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +  .page-post-list{
adicionado

2021-04-14 20:17 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +  <q-page class="bg-grey-2 q-pa-lg page-posts-preview">
alterado

2021-04-14 20:21 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +    &__category{
sem eu definir altura nessa div, fica da seguinte forma: 
![image](https://user-images.githubusercontent.com/79236683/114773647-b2066580-9d45-11eb-8e88-8b6776990395.png)

eu definindo altura, fica assim:
![image](https://user-images.githubusercontent.com/79236683/114773743-cd717080-9d45-11eb-8002-0b17ca619513.png)

2021-04-14 20:21 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +    &__category{
pra assim eu colocar minha tag de categoria posicionada no lugar desejado

2021-04-14 20:29 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +  .page-posts-preview{
adicionado

2021-04-14 21:52 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +    &__edit{
para alinhar os botões em lugares definidos no scss

2021-04-14 21:54 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      this.addPost({ urlMainImage: this.urlMainImage, category: this.selectedCategory, title: this.title, shortDescription: this.shortDescription, authorName: this.selectedAuthor, postDate: this.post
objeto values criado na pag de criação, edição e de visualização

2021-04-15 00:33 UTC, DouglasCalora requested changes

2021-04-15 00:33 UTC, DouglasCalora commented on src/components/CardPost.vue
> +        <img :src="content.urlMainImage" :alt="content.title" >
Remover espaço desnecessario no final da tag

2021-04-15 00:33 UTC, DouglasCalora commented on src/components/CardPost.vue
> +        <p><span class="card-post__category">{{ content.category }}</span></p>
Pq esse span? não daria pra fazer td no `p`?

2021-04-15 00:33 UTC, DouglasCalora commented on src/helpers/methods/formatDateTime.js
> +function formatDateTime (value, mask = 'DD/MM/YYYY HH:mm:ss') {
como é apenas um unico metodo pq não usa `export default`?

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/authors/AuthorsList.vue
> +      titulo: 'teste',
Continua em portugues

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +        </div>
Remover os espaços dentro do `[ ]`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +        <q-editor class="q-my-lg bg-grey-2" v-model="mainText" :definitions="{ bold: {label: 'Bold', icon: null} }"/>
se icon é null tem necessidade de passar? e falta espaço antes da key label

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +          <q-btn color="primary" flat label="Cancelar" @click="confirmCancel" />
confirmCancel? me parece meio contraditorio

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +
remover espaço

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +      urlMainImage: '',
`mainImageURL`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +      categoryOptions: ['Esportes', 'Tecnologia', 'Culinária', 'Mercado Financeiro', 'Animais', 'Brasil', 'Exterior', 'Outros'],
essa linha esta passando das 120 col? se sim quebre ela

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +      confirmCancelData: false
Mesma coisa sobre estar contraditorio

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +      this.postDate = formatDateTime(new Date())
este `new Date` deveria estar dentro do forrmatDateTime, caso vc n passe uma data vc da um new date internamente

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +      return !!(this.validateRequiredFields(this.urlMainImage) || (this.validateRequiredFields(this.title)) ||
Concordo! @eliasassuncao

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsEdit.vue
> +          label="Informe a categoria da postagem*" :rules="[ validateRequiredFields ]" />
remover espaço do [ ]

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsEdit.vue
> +    <q-page class="bg-grey-2 q-pa-lg">
Mesmos comentarios referente a pagina de criar, alias, poderia ser a mesma pagina, deferenciando a ação de `criar/editar` pela `rota`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsList.vue
> +                  <q-input filled v-model="calendarDate" mask="date" :rules="['date']" class="q-mt-md">
este rules 'date' esta correto?

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsList.vue
> +                  <q-btn color="primary" flat label="Limpar" @click="cleanFilters" />
`clearFilters`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsList.vue
> +      this.$router.push({ name: 'PostsSingle', params: { id: index } })
No caso o parametro de  `id`, não? @eliasassuncao

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsList.vue
> +  .page-post-list{
o correto é `.page-posts-list`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsList.vue
> +    &__edit{
Este nome esta estranho, se eu te falar que tenho uma classe "edit" o que vc pensa que ela faz internamente no css? e a indentação esta errada, falta um espaço.

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsSingle.vue
> +      urlMainImage: '',
mainImageURL

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsSingle.vue
> +    loadValues () {
`setValues`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsSingle.vue
> +    idPost () {
`postId` ou somente `id`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsSingle.vue
> +  .page-posts-preview{
ainda está sem

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsSingle.vue
> +    &__category{
está sem o espaçamento

2021-04-15 00:33 UTC, DouglasCalora commented on src/store/modules/posts.js
> +  addPost ({ commit }, value) {
seguindo a logica deveria se chamar `setPost`

2021-04-15 00:33 UTC, DouglasCalora commented on src/components/CardPost.vue
>      &__category{
faltou espaço depois do nome da classe

2021-04-15 00:33 UTC, DouglasCalora commented on src/components/CardPost.vue
>      &__author{
faltou espaço depois do nome da classe

2021-04-15 00:33 UTC, DouglasCalora commented on src/components/CardPost.vue
>        & p{
faltou espaço depois do nome da classe

2021-04-15 00:33 UTC, DouglasCalora commented on src/components/CardPost.vue
>        & p{
E tente evitar fazer isto direto pela tag, tente por uma classe

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +      this.addPost({ urlMainImage: this.urlMainImage, category: this.selectedCategory, title: this.title, shortDescription: this.shortDescription, authorName: this.selectedAuthor, postDate: this.post
E a chave seria `mainImageURL`

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +      })
adc espaço

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsCreate.vue
> +    confirmCancel () {
Mesma coisa sobre o nome estar contraditorio

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsEdit.vue
> +        'Outros'],
deixar a chave sozinha na linha debaixo

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsEdit.vue
> +      }
espaço

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsEdit.vue
> +    this.loadInputValues()
setInputValues não?

2021-04-15 00:33 UTC, DouglasCalora commented on src/pages/posts/PostsList.vue
> +        'Outros'],
deixar a chave sozinha na linha debaixo

2021-04-15 13:10 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      this.addPost({ urlMainImage: this.urlMainImage, category: this.selectedCategory, title: this.title, shortDescription: this.shortDescription, authorName: this.selectedAuthor, postDate: this.post
alterado

2021-04-15 14:14 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +          <q-dialog v-model="confirmCancelData" persistent>
realizado

2021-04-15 14:15 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +      authorsList: 'authors/authorsList'
feito

2021-04-15 14:15 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="selectedAuthor" :options='authorsOptions' label="Autor" />
alterado

2021-04-15 14:17 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +                  <q-select v-model="selectedCategory" :options='categoryOptions' label="Categoria" />
alterado

2021-04-15 14:18 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +        values: {
alterado

2021-04-15 14:21 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +    idPost () {
alterado

2021-04-15 14:21 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +    <div v-if="checkListSizeForPagination()" class="q-pa-lg flex flex-center">
alterado

2021-04-15 14:25 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +    &__edit{
alterado para edit-button

2021-04-15 14:26 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +        <img :src="content.urlMainImage" :alt="content.title" >
removido

2021-04-15 14:37 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      this.$router.push({ name: 'PostsSingle', params: { id: index } })
sim, falei errado hehe

2021-04-15 14:39 UTC, felipejuzo02 commented on src/helpers/methods/formatDateTime.js
> +function formatDateTime (value, mask = 'DD/MM/YYYY HH:mm:ss') {
resolvido

2021-04-15 14:39 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +        </div>
removido

2021-04-15 14:49 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +    confirmCancel () {
tudo sobre o cancelar foi movido para um componente e o nome do método foi alterado

2021-04-15 14:51 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +        'Outros'],
ajustado

2021-04-15 14:54 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +      }
alterado

2021-04-15 14:54 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +    this.loadInputValues()
alterado

2021-04-15 14:55 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +        'Outros'],
alterado

2021-04-15 14:56 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +        <q-editor class="q-my-lg bg-grey-2" v-model="mainText" :definitions="{ bold: {label: 'Bold', icon: null} }"/>
as definições foram removidas ficando somente:
![image](https://user-images.githubusercontent.com/79236683/114890668-9bade780-9de1-11eb-8152-b87c7a50ccbb.png)

2021-04-15 14:57 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +          <q-btn color="primary" flat label="Cancelar" @click="confirmCancel" />
Cancelamento foi movido para um componente e nome do método alterado

2021-04-15 14:57 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +
ajustado

2021-04-15 14:57 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      urlMainImage: '',
ajustado

2021-04-15 14:58 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      categoryOptions: ['Esportes', 'Tecnologia', 'Culinária', 'Mercado Financeiro', 'Animais', 'Brasil', 'Exterior', 'Outros'],
estavam passando sim. Linha quebrada

2021-04-15 14:59 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      confirmCancelData: false
Alterado

2021-04-15 15:03 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      this.postDate = formatDateTime(new Date())
alterado

2021-04-15 15:06 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +          label="Informe a categoria da postagem*" :rules="[ validateRequiredFields ]" />
alterado

2021-04-15 15:06 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +      urlMainImage: '',
alterado

2021-04-15 15:08 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +                  <q-btn color="primary" flat label="Limpar" @click="cleanFilters" />
alterado

2021-04-15 15:15 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +  .page-post-list{
alterado

2021-04-15 15:18 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +    &__category{
adicionado

2021-04-15 15:21 UTC, felipejuzo02 commented on src/store/modules/posts.js
> +  addPost ({ commit }, value) {
alterado

2021-04-15 15:22 UTC, felipejuzo02 commented on src/components/CardPost.vue
>      &__category{
adicionado

2021-04-15 15:23 UTC, felipejuzo02 commented on src/components/CardPost.vue
>      &__author{
adicionado

2021-04-15 15:23 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +    idPost () {
alterado para postId

2021-04-15 15:24 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +    loadValues () {
alterado

2021-04-15 15:26 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +                  <q-input filled v-model="calendarDate" mask="date" :rules="['date']" class="q-mt-md">
parte de filtros, foi realizado apenas a estrutura para layout, funcionamento irei adicionar logo mais

2021-04-15 15:27 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      })
adicionado

2021-04-15 17:06 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      this.$router.push({ name: 'PostsSingle', params: { id: index } })
alterado

2021-04-15 17:16 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +    loadValues () {
resolvido

2021-04-15 20:45 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +      this.urlMainImage = this.posts[this.idPost].urlMainImage
alterado

2021-04-15 20:47 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +    <q-page class="bg-grey-2 q-pa-lg">
Criada a PostsForm para deixar tudo na mesma página e diferenciando as ações pela rota. Ainda vou deixar as páginas de Edit e Create, até estiver totalmente validado, após irei remove-las

2021-04-15 20:59 UTC, felipejuzo02 commented on src/components/CardPost.vue
>        & p{
ajustado

2021-04-16 14:51 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      return !!(this.validateRequiredFields(this.urlMainImage) || (this.validateRequiredFields(this.title)) ||
Resolvido

2021-04-16 14:51 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +      return !!(this.validateRequiredFields(this.urlMainImage) || (this.validateRequiredFields(this.title)) ||
Resolvido

2021-04-16 15:11 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      this.selectedAuthor = ''
alterado

2021-04-16 19:06 UTC, eliasassuncao requested changes

2021-04-16 19:06 UTC, eliasassuncao commented on src/pages/posts/PostsCreate.vue
> +      return !!(this.validateRequiredFields(this.values.mainImageURL) || (this.validateRequiredFields(this.values.title)) ||
seria melhor alguma lógica pra loopar e validar, código está muito extenso

2021-04-16 19:06 UTC, eliasassuncao commented on src/pages/posts/PostsEdit.vue
> +      return !!(this.validateRequiredFields(this.values.mainImageURL) || (this.validateRequiredFields(this.values.title)) ||
seria melhor alguma lógica pra loopar e validar, código está muito extenso

2021-04-16 19:06 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +        if (this.validateRequiredFields(this.values[key]) === 'Campo obrigatório') {
só `if (this.validateRequiredFields(this.values[key]))`  não funcionaria?

2021-04-16 19:06 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      for (var objKey in this.selectedValues) {
utilizar let ao invés de var

2021-04-16 19:06 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +    checkListSizeForPagination () {
`hasPagination` não melhor?

2021-04-16 19:06 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
>        position: absolute;
existe classe `àbsolute` do quasar pra isso

2021-04-16 19:06 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +<template>
Se existe o `postsForm`, não deveria não existir um `postsEdit` e `postsCreate`   ?

2021-04-16 19:31 UTC, felipejuzo02 commented on src/pages/posts/PostsCreate.vue
> +      return !!(this.validateRequiredFields(this.values.mainImageURL) || (this.validateRequiredFields(this.values.title)) ||
Página do post create não está sendo mais utilizada, a lógica foi para PostsForm

2021-04-16 19:32 UTC, felipejuzo02 commented on src/pages/posts/PostsEdit.vue
> +      return !!(this.validateRequiredFields(this.values.mainImageURL) || (this.validateRequiredFields(this.values.title)) ||
Página do post edit não está sendo mais utilizada, a lógica foi para PostsForm

2021-04-16 19:33 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +<template>
Sim, concordo, mas conforme conversado, ainda vou deixar as páginas até validar a PostsForm. Segundo testes, o funcionamente está correto, mas melhor segurar um pouco mais para exclusão

2021-04-16 19:40 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
>        position: absolute;
alterado

2021-04-16 19:43 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +    checkListSizeForPagination () {
alterado

2021-04-16 19:44 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +        if (this.validateRequiredFields(this.values[key]) === 'Campo obrigatório') {
Sim, ótimo ponto levantado. Já alterado

2021-04-16 19:48 UTC, felipejuzo02 commented on src/pages/authors/AuthorsCreate.vue
> +import modalCancel from 'src/components/modalCancel.vue'
removido

2021-04-16 19:50 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      for (var objKey in this.selectedValues) {
auto correção sugere, const ao invés de let

2021-04-16 19:51 UTC, eliasassuncao requested changes

2021-04-16 19:51 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      right: -10px;
negativo? tem necessidade?

2021-04-16 19:52 UTC, felipejuzo02 commented on src/components/modalCancel.vue
> +    pageToAccess: {
alterado

2021-04-16 19:54 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      <div class="card-post__main-area relative-position">
ajustado

2021-04-16 20:18 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +        <p class="card-post__author-name">Data de postagem: <span class="card-post__author-name--primary-color">{{ content.postDate }}</span></p>
alterado

2021-04-16 20:18 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      right: -10px;
removido

2021-04-16 20:19 UTC, felipejuzo02 commented on src/components/CardPost.vue
>        <div class="card-post__author">
não, pois preciso mexer em algo apenas no bloco da div e depois mexer em outra apenas no bloco de author-name

2021-04-19 15:05 UTC, eliasassuncao requested changes

2021-04-19 15:05 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      margin-bottom: 0;
utilizar classe do quasar `q-mb-none`

2021-04-19 15:07 UTC, eliasassuncao requested changes

2021-04-19 15:07 UTC, eliasassuncao commented on src/components/CardPost.vue
> +        height: 50%;
espaçamento a mais

2021-04-19 15:07 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      background-color: rgb(243, 243, 243);
utilizar hexa: `#F3F3F3`

2021-04-19 15:27 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +        height: 50%;
ajustado

2021-04-19 15:27 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      background-color: rgb(243, 243, 243);
ajustado

2021-04-19 15:30 UTC, felipejuzo02 commented on src/components/CardPost.vue
> +      margin-bottom: 0;
resolvido

2021-04-19 15:59 UTC, eliasassuncao approved these changes

2021-04-19 15:59 UTC, eliasassuncao commented on src/components/CardPost.vue
> +      </div>
identação me parece errada

2021-04-19 16:58 UTC, DouglasCalora approved these changes

2021-04-19 17:16 UTC, merged