Exclusion of authors
felipejuzo02/quasar-blog pull request #6
Opened 2021-04-27 21:33 UTC by felipejuzo02

2021-04-27 21:43 UTC, eliasassuncao requested changes

2021-04-27 21:43 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +          <q-btn flat color="negative" icon="delete" label="Deletar autor" @click="this.confirmDelete" />
não precisa do this

2021-04-27 21:43 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +                <q-btn label="Confirmar" color="primary" v-close-popup @click="this.deleteAuthor" />
não precisa do this

2021-04-27 21:43 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +      removeAuthor: 'authors/removeAuthor'
deleteAuthor ficaria melhor

2021-04-27 21:43 UTC, eliasassuncao commented on src/store/modules/authors.js
> +  async removeAuthor (content, id) {
context ao invés de content

2021-04-27 21:46 UTC, felipejuzo02 commented on src/pages/authors/AuthorsForm.vue
> +          <q-btn flat color="negative" icon="delete" label="Deletar autor" @click="this.confirmDelete" />
removido

2021-04-27 21:46 UTC, felipejuzo02 commented on src/pages/authors/AuthorsForm.vue
> +                <q-btn label="Confirmar" color="primary" v-close-popup @click="this.deleteAuthor" />
removido

2021-04-27 21:47 UTC, felipejuzo02 commented on src/store/modules/authors.js
> +  async removeAuthor (content, id) {
alterado

2021-04-27 21:51 UTC, felipejuzo02 commented on src/pages/authors/AuthorsForm.vue
> +      removeAuthor: 'authors/removeAuthor'
alterado, mas tive que alterar o nome meu método que chamo no click para não dar duplicidade no nome

2021-04-28 14:27 UTC, eliasassuncao approved these changes

2021-04-28 14:27 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +      this.deleteAuthor(id)
async await, pq pode acontecer do `fetch` acontecer antes do delete, por ser assíncrono

2021-04-28 14:42 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +      this.deleteAuthor(id)
alterado

2021-04-28 15:34 UTC, cassioalmeida2 approved these changes

2021-04-28 15:46 UTC, merged