Feature/post api
felipejuzo02/quasar-blog pull request #7
Opened 2021-04-28 19:38 UTC by felipejuzo02

2021-04-28 19:53 UTC, cassioalmeida2 commented on src/pages/posts/PostsForm.vue
> +        <q-btn :disable="validateForm" color="primary" @click="actionChoose">{{ buttonNameToSave }}</q-btn>
porque buttonNameToSave? o que essa descrição exibe?

2021-04-28 20:48 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +        <q-btn :disable="validateForm" color="primary" @click="actionChoose">{{ buttonNameToSave }}</q-btn>
Serve para exibir o nome do botão dependendo da rota, ou seja, caso seja rota de criação, seja 'Criar'. Alterei para `submitButtonLabel`, ao meu ver ficou melhor que antes

2021-04-29 14:34 UTC, eliasassuncao requested changes

2021-04-29 14:43 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
>          <p class="text-h5 q-mb-xs">{{ definitionOfPageName }}</p>
definição do nome da pagina

2021-04-29 14:44 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +          <q-dialog v-model="confirmDeleteData" persistent>
pra cancelar sim, mas pra confirmar deleção não, vou criar o modal pra essa confirmação dps

2021-04-29 14:53 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      this.fetchPosts()
alterado

2021-04-29 14:53 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +    this.fetchAuthors()
adicionado

2021-04-29 14:54 UTC, felipejuzo02 commented on src/store/modules/posts.js
> +      commit('deletePost', id)
alterado

2021-04-29 14:58 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
>          <p class="text-h5 q-mb-xs">{{ definitionOfPageName }}</p>
alterei para pageTitle

2021-04-29 18:44 UTC, eliasassuncao requested changes

2021-04-29 18:44 UTC, eliasassuncao commented on src/components/modalDelete.vue
> +    <q-btn flat color="negative" icon="delete" label="Deletar autor" @click="confirmDelete" />
esse componente deveria ser somente o modal, o botão vc coloca do lado de fora não? pra ter mais um controle do layout

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +        <modal-cancel hasPagination="AuthorsList" />
nome me parece errado, vc está afirmando uma coisa e o valor não é booleano

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +import modalDelete from 'src/components/modalDelete'
precisa ser o path inteiro? somente `components/modalCancel` não funciona?

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +        <modal-delete @click="deleteListPost" />
esse if não poderia estar no `modal-delete` ?

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +        <modal-delete @click="deleteListAuthor" />
esse if não poderia estar no `modal-delete` ?

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +import modalDelete from 'src/components/modalDelete'
path `components/modalDelete` não funciona?

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
>        this.$router.push({ name: 'PostsList' })
se vc já está indo pra tela de listagem após criar, tem necessidade de utilizar o `await this.fetchPosts()` ? vc vai estar buscando 2x

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      await this.fetchPosts()
se vc já está indo pra tela de listagem após editar, tem necessidade de utilizar o await this.fetchPosts() ? vc vai estar buscando 2x

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      await this.fetchPosts()
se vc já está indo pra tela de listagem após deletar, tem necessidade de utilizar o await this.fetchPosts() ? vc vai estar buscando 2x.

E isso na verdade nem está está buscando, pq vc joga o cara pra página `postsLists` antes da função `fetchPosts`

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +    this.fetchAuthors()
está duplicando a busca, no `setInputValues` e no created

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +      fetchPost: 'posts/fetchPost'
só contém uma chave, poderia estar tudo em uma linha só.

2021-04-29 18:44 UTC, eliasassuncao commented on src/store/modules/authors.js
> +  deleteAuthor (state, id) {
precisa desse splice?

2021-04-29 18:44 UTC, eliasassuncao commented on src/store/modules/authors.js
> +      commit('deleteAuthor', id)
faz sentido esse commit? vc já está fazendo o delete pela api

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
>        return this.isCreate ? 'Criar Postagem' : 'Editar postagem'
uma outra forma seria `return ${this.isCreate ? 'Criar' : 'Editar' } postagem` (utilizando template string, crase, não coloquei pq aqui pq o comentário fica zoado.), mas tanto faz.

2021-04-29 18:44 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      await this.fetchPosts()
se vc já está indo pra tela de listagem após criar, tem necessidade de utilizar o await this.fetchPosts() ? vc vai estar buscando 2x

2021-04-29 19:23 UTC, felipejuzo02 commented on src/components/modalDelete.vue
> +    <q-btn flat color="negative" icon="delete" label="Deletar autor" @click="confirmDelete" />
alterado

2021-04-29 19:30 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +        <modal-delete @click="deleteListPost" />
se o botão for ficar pelo lado de fora, não. O botão só irá aparecer dependendo dessa verificação

2021-04-29 19:36 UTC, felipejuzo02 commented on src/pages/authors/AuthorsForm.vue
> +        <modal-delete @click="deleteListAuthor" />
se o botão for ficar pelo lado de fora, não. O botão só irá aparecer dependendo dessa verificação

2021-04-29 19:36 UTC, felipejuzo02 commented on src/pages/authors/AuthorsForm.vue
> +        <modal-cancel hasPagination="AuthorsList" />
alterado

2021-04-29 19:37 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +import modalDelete from 'src/components/modalDelete'
alterado

2021-04-29 19:42 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
>        this.$router.push({ name: 'PostsList' })
removido

2021-04-29 19:42 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      await this.fetchPosts()
removido

2021-04-29 19:43 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      await this.fetchPosts()
alterado

2021-04-29 19:47 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +    this.fetchAuthors()
na vdd não, um é pra carregar minha lista de autores, tanto na criação quanto na edição e o outro chamado apenas na edição para carregar com os valores daquele autor em especifico

2021-04-29 19:48 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +      fetchPost: 'posts/fetchPost'
alterado

2021-04-29 19:51 UTC, felipejuzo02 commented on src/store/modules/authors.js
> +  deleteAuthor (state, id) {
removido

2021-04-29 19:52 UTC, felipejuzo02 commented on src/store/modules/authors.js
> +      commit('deleteAuthor', id)
removido

2021-04-29 19:54 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      await this.fetchPosts()
removido

2021-04-30 14:49 UTC, eliasassuncao requested changes

2021-04-30 14:49 UTC, eliasassuncao commented on src/components/modalCancel.vue
>    <div>
precisa da div?

2021-04-30 14:49 UTC, eliasassuncao commented on src/components/modalCancel.vue
> +    <q-dialog v-model="cancellationConfirmationData" persistent>
nome de v-model muito extenso, e se vc utilizar o `v-on="$listeners"` vc pode passar o v-model lá fora

2021-04-30 14:49 UTC, eliasassuncao commented on src/components/modalCancel.vue
> +    cancellationConfirmationData: {
v-model pode ficar do lado de fora.

2021-04-30 14:49 UTC, eliasassuncao commented on src/components/modalDelete.vue
> +  <q-dialog v-model="confirmDeleteData" persistent>
v-model pode ficar do lado de fora

2021-04-30 14:49 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      this.values.postDate = formatDateTime()
o que esse helper `formatDateTime` faz? vc não tá passando valor pra ele formatar?

2021-04-30 14:49 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      return `${this.isCreate ? 'Criar' : 'Editar'}` + ' postagem'
não precisa do +..., vc inclui dentro da template string

2021-04-30 14:49 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +        <modal-cancel :cancellationConfirmationData="cancellationConfirmationData" routeName="AuthorsList" />
nome de v-model muito extenso

2021-04-30 14:50 UTC, cassioalmeida2 commented on src/components/modalCancel.vue
> +    <q-dialog v-model="cancellationConfirmationData" persistent>
o que esse persistent faz?

2021-04-30 14:53 UTC, felipejuzo02 commented on src/components/modalCancel.vue
>    <div>
não, ja retirei

2021-04-30 14:54 UTC, felipejuzo02 commented on src/components/modalCancel.vue
> +    <q-dialog v-model="cancellationConfirmationData" persistent>
não deixa eu fechar meu dialog sem clicar em algum botão

2021-04-30 14:55 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      return `${this.isCreate ? 'Criar' : 'Editar'}` + ' postagem'
alterado

2021-04-30 15:12 UTC, felipejuzo02 commented on src/components/modalCancel.vue
> +    cancellationConfirmationData: {
alterado

2021-04-30 15:12 UTC, felipejuzo02 commented on src/pages/authors/AuthorsForm.vue
> +        <modal-cancel :cancellationConfirmationData="cancellationConfirmationData" routeName="AuthorsList" />
alterado para `confirmDeleteData`

2021-04-30 15:17 UTC, felipejuzo02 commented on src/components/modalDelete.vue
> +  <q-dialog v-model="confirmDeleteData" persistent>
alterado

2021-04-30 15:19 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      this.values.postDate = formatDateTime()
esse helper pega a hora atual dentro dele mesmo. Essa alteração fiz conforme sugestão do Doug

2021-04-30 15:35 UTC, eliasassuncao approved these changes

2021-04-30 15:35 UTC, eliasassuncao commented on src/components/modalDelete.vue
> +  props: {
props não utilizada

2021-04-30 15:35 UTC, eliasassuncao commented on src/pages/authors/AuthorsForm.vue
> +      <div>
precisa dessa div?

2021-04-30 15:36 UTC, felipejuzo02 commented on src/components/modalDelete.vue
> +  props: {
resolvido

2021-04-30 15:36 UTC, felipejuzo02 commented on src/pages/authors/AuthorsForm.vue
> +      <div>
resolvido

2021-04-30 19:47 UTC, cassioalmeida2 commented on src/pages/posts/PostsForm.vue
> +        <q-btn :disable="validateForm" color="primary" @click="actionChoose">{{ buttonNameToSave }}</q-btn>
faz mais sentido mesmo. ok!

2021-04-30 19:47 UTC, cassioalmeida2 commented on src/components/modalCancel.vue
> +    <q-dialog v-model="cancellationConfirmationData" persistent>
top!

2021-04-30 19:47 UTC, cassioalmeida2 approved these changes

2021-04-30 20:36 UTC, merged