Filter Posts
felipejuzo02/quasar-blog pull request #8
Opened 2021-05-04 22:18 UTC by felipejuzo02

2021-05-05 15:21 UTC, eliasassuncao requested changes

2021-05-05 15:21 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      this.values.postDate = this.formatDateTime()
precisa do `this`?

2021-05-05 15:21 UTC, eliasassuncao commented on src/pages/posts/PostsForm.vue
> +      this.values.editDate = this.formatDateTime()
precisa do `this`?

2021-05-05 15:21 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      filterData: {
somente `filters` ficaria melhor

2021-05-05 15:22 UTC, eliasassuncao requested changes

2021-05-05 15:22 UTC, eliasassuncao commented on src/store/modules/posts.js
> +        params: filter
se o `filter` chamasse params, vc poderia passar somente 1 chave
```

 const { data } = await axios({
        method: 'GET',
        url: 'posts',
        params
...
```

2021-05-05 15:32 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      this.values.postDate = this.formatDateTime()
não. já removi

2021-05-05 15:32 UTC, felipejuzo02 commented on src/pages/posts/PostsForm.vue
> +      this.values.editDate = this.formatDateTime()
nao. já removi

2021-05-05 15:33 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      filterData: {
alterado

2021-05-05 15:33 UTC, felipejuzo02 commented on src/store/modules/posts.js
> +        params: filter
alterado

2021-05-05 20:02 UTC, eliasassuncao approved these changes

2021-05-05 22:50 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
> +        <q-input debounce="1000" @input="filterPost" v-model="filters.title" label="Procurar" class="page-posts-list__search col" />
esse col sozinho funciona? para que é utilizado nessa forma?

2021-05-05 22:50 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
>                          <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
o que esse popup-proxy faz?

2021-05-06 12:33 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +        <q-input debounce="1000" @input="filterPost" v-model="filters.title" label="Procurar" class="page-posts-list__search col" />
esse col funciona para deixar meu input de pesquisar, do tamanho adequado de width. Sem ele fica da seguinte forma:
![image](https://user-images.githubusercontent.com/79236683/117298725-151f7f80-ae4e-11eb-9bcb-a63fe7af20b1.png)

Já com ele fica assim:
![image](https://user-images.githubusercontent.com/79236683/117298797-26688c00-ae4e-11eb-9a18-4b0e1c99ab36.png)

2021-05-06 12:40 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
>                          <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
ele serve pra abrir um popup do meu calendario, mas seu tamanho é de acordo com minha tela, abrindo o QMenu para as telas que forem maiores e para as menores abre um QDialog para ocupar melhor o espaço da tela

2021-05-06 13:49 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
> +        <q-input debounce="1000" @input="filterPost" v-model="filters.title" label="Procurar" class="page-posts-list__search col" />
legal então ele seria a abreviação do col-12 certo?

2021-05-06 13:50 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +        <q-input debounce="1000" @input="filterPost" v-model="filters.title" label="Procurar" class="page-posts-list__search col" />
não necessariamente. apenas col seria de forma automatica, o col 12 eu defino ele como todo o campo width

2021-05-06 13:56 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
>                          <q-popup-proxy ref="qDateProxy" transition-show="scale" transition-hide="scale">
ok!

2021-05-06 14:07 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +        <q-input debounce="1000" @input="filterPost" v-model="filters.title" label="Procurar" class="page-posts-list__search col" />
Para explicar melhor, caso eu use da seguinte forma:
![image](https://user-images.githubusercontent.com/79236683/117311808-ec51b700-ae5a-11eb-8267-3c71e3cb6332.png)
Com a class column na div pai, o comportamento é igual o col-12 sim.


Mas caso eu não use a class column na div pai da seguinte forma:
![image](https://user-images.githubusercontent.com/79236683/117312170-3a66ba80-ae5b-11eb-9eb9-a99d7f7655f7.png)
O col serve para completar apenas no espaço restante

2021-05-06 14:09 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
> +        <q-input debounce="1000" @input="filterPost" v-model="filters.title" label="Procurar" class="page-posts-list__search col" />
Boaa!

2021-05-06 14:32 UTC, cassioalmeida2 approved these changes

2021-05-06 14:32 UTC, merged