Pagination of the listing of post and authors. Adjustment in post pre…
felipejuzo02/quasar-blog pull request #9
Opened 2021-05-06 19:01 UTC by felipejuzo02

…view

2021-05-06 20:39 UTC, eliasassuncao requested changes

2021-05-06 20:39 UTC, eliasassuncao commented on db.json
>        "mainImageURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSERUTExMWFhUWFxoYFxcVFxUXGRcbGhgXFxcYFRcYHSggGRolHRYXIjEhJSkrLi4uGB8zODMsNygtLisBCgoKDg0OGxAQGy8mICUtLS0tLS0tLS0wL
esse mainImage não tá muito grande não? kkkkkk dificulta em visualizar a estrutura do db

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +          <p class="q-mb-lg">Ops... Não encontrei nenhum autor</p>
"Ops... nenhum autor encontrado" não seria melhor?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +      return this.authorsList.length >= 8 || this.pagination._page !== 1
se eu estiver na página 2 não tem paginação?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +          <q-pagination v-model="pagination._page" :max="5" direction-links boundary-links icon-first="skip_previous"
o click é onde? não deveria ser no `@input` ?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +    async authorsPagination () {
precisa dessa função? vc não pode passar o `fetchAuthors` direto lá?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      <p class="q-mb-lg">Ops... Não encontrei postagens.</p>
"Ops... nenhum post encontrado" não seria melhor?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      icon-last="skip_next" icon-prev="fast_rewind" icon-next="fast_forward" @click="filterPost" />
o click é onde? não deveria ser no @input ?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      return this.postsList.length >= 8 || this.pagination._page !== 1
se eu estiver na página 2 não tem paginação?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
>        <div v-html="values.mainText"></div>
não deveria ser 
```
<div>{{ values.mainText }} </div>
```
?

2021-05-06 20:39 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +      width: 50%;
estrutura estranha, não dá pra estruturar com grid?

2021-05-06 20:44 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
>        <div v-html="values.mainText"></div>
não por conta da estrutura do `q-editor`

2021-05-06 20:45 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      return this.postsList.length >= 8 || this.pagination._page !== 1
tem sim, essa comparação verifica se tenho mais de 8 posts ou se estou em uma pagina sem ser a primeira. Pois assim, se eu estiver na segunda pagina com 2 posts, a paginação aparece

2021-05-06 21:00 UTC, felipejuzo02 commented on db.json
>        "mainImageURL": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMSERUTExMWFhUWFxoYFxcVFxUXGRcbGhgXFxcYFRcYHSggGRolHRYXIjEhJSkrLi4uGB8zODMsNygtLisBCgoKDg0OGxAQGy8mICUtLS0tLS0tLS0wL
só aquele tanto kkkkkk, mas é o link da própria imagem

2021-05-06 21:11 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      <p class="q-mb-lg">Ops... Não encontrei postagens.</p>
fica melhor sim, alterado

2021-05-06 21:22 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +          <q-pagination v-model="pagination._page" :max="5" direction-links boundary-links icon-first="skip_previous"
alterado

2021-05-06 21:25 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +      return this.authorsList.length >= 8 || this.pagination._page !== 1
tem sim, essa comparação verifica se tenho mais de 8 posts ou se estou em uma pagina sem ser a primeira. Pois assim, se eu estiver na segunda pagina com 2 posts, a paginação aparece

2021-05-06 21:27 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +          <p class="q-mb-lg">Ops... Não encontrei nenhum autor</p>
alterado

2021-05-07 13:44 UTC, cassioalmeida2 commented on src/pages/posts/PostsSingle.vue
>      <q-separator color="primary" size="3px" />
Bem específico esse size, vai utilizar esse tamanho em outros locais ou só aqui mesmo? Se for só aqui tudo bem, porém se tiver em outros locais seria interessante criar uma variável para acessar nesses outros locais.

2021-05-07 13:44 UTC, cassioalmeida2 commented on src/pages/posts/PostsSingle.vue
> +      width: 50%;
tem um motivo específico para image nesse tamanho? seria melhor utilizar col-2, col-4...

2021-05-07 13:44 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
> +      return this.postsList.length >= 8 || this.pagination._page !== 1
não seria melhor utilizar nesses valores o _page e o _limit que vc criou lá em cima? São os mesmos valores.

2021-05-07 13:44 UTC, cassioalmeida2 commented on src/pages/posts/PostsList.vue
> +        _page: 1,
qual o motivo de usar o _ (underline) antes do atributo? Geralmente no padrão que temos não utilizamos dessa forma.

2021-05-07 18:33 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
>      <q-separator color="primary" size="3px" />
uso somente ai

2021-05-07 18:35 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +        _page: 1,
devido ser uma fake api, o json server tem que receber os parametros dessa forma.

2021-05-10 13:56 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +      width: 50%;
estrutura já conversado via dc

2021-05-10 20:03 UTC, eliasassuncao requested changes

2021-05-10 20:03 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +    teste () {
remover função de teste

2021-05-10 20:03 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +    this.teste()
remover função de teste

2021-05-10 20:03 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +      <div v-if="!$q.screen.gt.sm" class="text-h4 text-center text-primary">{{ values.title }}</div>
se vc só muda a classe, não poderia ser uma computada?

2021-05-10 20:03 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +      <img class="full-width q-my-md" :src="values.mainImageURL" :alt="values.title">
se vc só muda a classe, não poderia ser uma computada? ai não precisaria repetir os blocos

2021-05-10 21:29 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +    teste () {
removido

2021-05-10 21:29 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +    this.teste()
removido

2021-05-11 18:18 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +      <div v-if="!$q.screen.gt.sm" class="text-h4 text-center text-primary">{{ values.title }}</div>
não sabia dessa possibilidade. Já realizei o ajuste

2021-05-11 18:19 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +      <img class="full-width q-my-md" :src="values.mainImageURL" :alt="values.title">
não sabia dessa possibilidade. Já realizei o ajuste

2021-05-11 20:52 UTC, eliasassuncao requested changes

2021-05-11 20:52 UTC, eliasassuncao commented on src/pages/authors/AuthorsList.vue
> +            <p class="q-mb-none col ">{{ author.name }}</p>
espaçamento a mais

2021-05-11 20:52 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      return this.$q.screen.gt.sm ? 'q-col-gutter-md' : ''
pode ser `return this.$q.screen.gt.sm && 'q-col-gutter-md'`

2021-05-11 20:52 UTC, eliasassuncao commented on src/pages/posts/PostsList.vue
> +      return this.$q.screen.gt.sm ? '' : 'q-mb-md'
pode ser `return this.$q.screen.gt.sm && 'q-mb-md'`

2021-05-11 20:52 UTC, eliasassuncao commented on src/pages/posts/PostsSingle.vue
> +      <div v-if="!$q.screen.gt.sm" class="text-h4 text-center text-primary">{{ values.title }}</div>
ainda está sem a computada

2021-05-11 21:02 UTC, felipejuzo02 commented on src/pages/authors/AuthorsList.vue
> +            <p class="q-mb-none col ">{{ author.name }}</p>
removido

2021-05-11 21:25 UTC, felipejuzo02 commented on src/pages/posts/PostsList.vue
> +      return this.$q.screen.gt.sm ? '' : 'q-mb-md'
alterado

2021-05-11 21:26 UTC, felipejuzo02 commented on src/pages/posts/PostsSingle.vue
> +      <div v-if="!$q.screen.gt.sm" class="text-h4 text-center text-primary">{{ values.title }}</div>
alterado

2021-05-12 20:58 UTC, cassioalmeida2 approved these changes

2021-05-12 21:00 UTC, merged